### ISSUE TITLE
Test failure with dev version of httr

### ISSUE THREAD

**Issue by hadley** [ropensci/aRxiv#25]
```R
  > test_check("aRxiv")
  Loading required package: aRxiv
  arxiv_errors : ...
  arxiv_search in batches : 1
  cleaning the records : Error in arxiv_count(query) : arXiv error: incorrect id format for NA
  Calls: test_check ... all.equal.numeric -> attr.all.equal -> mode -> omit_attr -> arxiv_count
  Execution halted
```

Would you mind taking a look please?

**Comment by kbroman** [comment]
I'm getting this error from a call to `POST()`

    Error: 'new_handle' is not an exported object from 'namespace:curl'

I guess from [`httr::handle()`](https://github.com/hadley/httr/blob/master/R/handle.r#L27).

**Comment by hadley** [comment]
Did you update curl?

**Comment by kbroman** [comment]
Okay now I've got the dev version of curl, and I'm getting the error you're getting. Will investigate.

**Comment by kbroman** [comment]
Okay, I've figured some problems, but it seems like there are a bunch more. :frowning:

Initial bit is that I was doing

    httr::POST(query_url, body=list(search_query=query, id_list=possibly_null))

with the assumption that if `possible_null` were `NULL` then it would get dropped, which it no longer is.

**Comment by kbroman** [comment]
Hmm, actually that was the only problem. I'd just left some debug code in there. :smile_cat:

**Comment by kbroman** [comment]
Fixed in PR #26.

**Comment by hadley** [comment]
That sounds like a bug in httr to me...

**Comment by sckott** [comment]
ive noticed the same, that `POST`/etc. don't like it when `body` is `NULL` or an empty list

**Comment by hadley** [comment]
@sckott this is new? (like as of ~3 hours ago)

**Comment by sckott** [comment]
no, been happening a long time

**Comment by kbroman** [comment]
For completeness, here's what was going on:

This is okay:

    httr::POST("http://export.arxiv.org/api/query",
                body=list(search_query='au:"Karl W. Broman"'))

This used to work but doesn't with the devel version of httr:

    httr::POST("http://export.arxiv.org/api/query",
                body=list(search_query='au:"Karl W. Broman"', id_list=NULL))

**Comment by sckott** [comment]
what I was talking about was if `length(body) == 0` then `POST` would fail

**Comment by kbroman** [comment]
Hmm. Using `list()` as the body actually works for me: gives status 200 and an appropriate response with 0 results.

    z <- httr::POST("http://export.arxiv.org/api/query", body=NULL)
    aRxiv::result2list(z)

When using `list()` as the body, however, `httr::POST` throws an error in [line 47 of `body.R`](https://github.com/hadley/httr/blob/6e4fdf9a1be1e13a6a0e35fb65b1719752952136/R/body.R#L47)

    stopifnot(length(names(body)) > 0)

**Comment by hadley** [comment]
Fixed in https://github.com/hadley/httr/commit/6d06ad571316dcba5944a5e545c374b64d6979d6

The behaviour is now consistent with query params, and there's a better message if all the body parameters aren't named.
