### ISSUE TITLE
NEWS and releases

### ISSUE THREAD

**Issue by sckott** [ropensci/aRxiv#30]
hi @kbroman - would you mind using a `NEWS` file, and tag each CRAN release with relevant `NEWS` section for that tag in github Releases https://github.com/ropensci/arxiv/releases ?   

would be easier to see what's been changed in each version :)

**Comment by kbroman** [comment]
Will do.

**Comment by sckott** [comment]
thx

**Comment by kbroman** [comment]
It was a bit tricky getting the right dates on the releases, but with PR #31, I've added a NEWS file and tagged the CRAN releases.
