### ISSUE TITLE
put NEWS bits in releases

### ISSUE THREAD

**Issue by sckott** [ropensci/aRxiv#36]
hey @kbroman  - We want all rOpenSci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  

* you already keep a `NEWS` file, thanks!
* thanks for git tagging!
* Could you please use the [releases tab](https://github.com/ropensci/aRxiv/releases) on this repo to include the associated NEWS items for each tag/version ? thanks 😄

**Comment by kbroman** [comment]
Will do, thanks.

**Comment by sckott** [comment]
thank!
