### ISSUE TITLE
The list of categories in the package is out of date

### ISSUE THREAD

**Issue by vagdur** [ropensci/aRxiv#56]
For example "cs.SI" is not in the list of categories in `arxiv_cats`, but does exist on the actual arXiv and is possible to search for.

**Comment by kbroman** [comment]
Thanks!

It looks like the information on subject classifications has moved. It was previously in a table at <http://arxiv.org/help/api/user-manual>, but it's now shown at <https://arxiv.org/category_taxonomy>.

The query term information appears unchanged, is a table within <https://arxiv.org/help/api/user-manual.html>

I'll need to revise the script to grab this information, [`grab_api_manual_tables.R`](https://github.com/ropensci/aRxiv/blob/master/inst/scripts/grab_api_manual_tables.R).

**Comment by kbroman** [comment]
Fixed; the arxiv_cats dataset now has five columns (and 155 rows).
